<div class="h-products">
    <ul>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
$categoryId = 42; // YOUR CATEGORY ID
$category = $categoryFactory->create()->load($categoryId);
$categoryProducts = $category->getProductCollection()
    ->addAttributeToSelect('*')
    ->setPageSize(4);
foreach ($categoryProducts as $product)
{
    $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
    ?>
        <li>
            <a href="<?= $product->getProductUrl(); ?>">
                <img src="<?= $imageUrl;?>" >
                <h3><?= $product->getName(); ?></h3>
            </a>
            <p>$<?= $product->getPrice(); ?></p>
            <strong> &#9733;&#9733;&#9733;&#9733;&#9733;</strong>
        </li>
    <?php
}
?>
</ul>
</div>
<a href="https://www.socalpatio.com/dining-sets.html">
<h2 style="background: #E7E9E9;
    color: #01b7b8;text-align: center;font-weight: 600;padding: 5px;border-bottom: 2px solid;">Shop All Dining Sets</h2>
</a><br><br><br>
<div class="h-products">
    <ul>
        <?php
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
        $categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
        $categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
        $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
        $categoryId = 43; // YOUR CATEGORY ID
        $category = $categoryFactory->create()->load($categoryId);
        $categoryProducts = $category->getProductCollection()
            ->addAttributeToSelect('*')
            ->setPageSize(4);
        foreach ($categoryProducts as $product)
        {
            $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
            ?>
            <li>
                <a href="<?= $product->getProductUrl(); ?>">
                    <img src="<?= $imageUrl;?>" >
                    <h3><?= $product->getName(); ?></h3>
                </a>
                <p>$<?= $product->getPrice(); ?></p>
                <strong> &#9733;&#9733;&#9733;&#9733;&#9733;</strong>
            </li>
            <?php
        }
        ?>
    </ul>
</div>
<a href="https://www.socalpatio.com/bar-sets.html">
<h2 style="background: #E7E9E9;
    color: #01b7b8;text-align: center;font-weight: 600;padding: 5px;border-bottom: 2px solid;">Shop All Bar Sets</h2>
</a><br><br><br>
<div class="h-products">
    <ul>
        <?php
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
        $categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
        $categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
        $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
        $categoryId = 44; // YOUR CATEGORY ID
        $category = $categoryFactory->create()->load($categoryId);
        $categoryProducts = $category->getProductCollection()
            ->addAttributeToSelect('*')
            ->setPageSize(4);
        foreach ($categoryProducts as $product)
        {
            $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
            ?>
            <li>
                <a href="<?= $product->getProductUrl(); ?>">
                    <img src="<?= $imageUrl;?>" >
                    <h3><?= $product->getName(); ?></h3>
                </a>
                <p>$<?= $product->getPrice(); ?></p>
                <strong> &#9733;&#9733;&#9733;&#9733;&#9733;</strong>
            </li>
            <?php
        }
        ?>
    </ul>
</div>
<a href="https://www.socalpatio.com/deep-seating-sets.html">
<h2 style="background: #E7E9E9;
    color: #01b7b8;text-align: center;font-weight: 600;padding: 5px;border-bottom: 2px solid;">Shop All Deep Seating Sets</h2>
</a>